dist: bionic
language: c++
sudo: true

git:
  depth: 10
  submodules: false

services:
  - docker

matrix:
  include:
    - env: COMPILER=gcc-4.9.4   BUILD_TYPE=Release
    - env: COMPILER=gcc-5.5.0   BUILD_TYPE=Release
    - env: COMPILER=gcc-6.5.0   BUILD_TYPE=Release
    - env: COMPILER=gcc-7.4.0   BUILD_TYPE=Release
    - env: COMPILER=gcc-8.3.0   BUILD_TYPE=Release
    - env: COMPILER=gcc-9.2.0   BUILD_TYPE=Release
    - env: COMPILER=clang-3.9.1 BUILD_TYPE=Release
    - env: COMPILER=clang-5.0.2 BUILD_TYPE=Release
    - env: COMPILER=clang-6.0.0 BUILD_TYPE=Release
    - env: COMPILER=clang-7.1.0 BUILD_TYPE=Release
    - env: COMPILER=clang-8.0.0 BUILD_TYPE=Release
    - env: COMPILER=clang-9.0.0 BUILD_TYPE=Release
    - env: COMPILER=gcc-9.2.0   BUILD_TYPE=Debug

before_install:
  - docker pull mariokonrad/marnav:${COMPILER}

script:
  - bin/docker-build.sh ${COMPILER} ${BUILD_TYPE}
  - bin/docker-run.sh mariokonrad/marnav:${COMPILER} bin/test-library.sh

